# CMake generated Testfile for 
# Source directory: D:/Git/dcmtk/dcmsr/tests
# Build directory: D:/Git/dcmtk/VisualStudio/dcmsr/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(dcmsr_addTreeNode "D:/Git/dcmtk/VisualStudio/bin/dcmsr_tests" "dcmsr_addTreeNode")
set_tests_properties(dcmsr_addTreeNode PROPERTIES  LABELS "dcmsr")
add_test(dcmsr_treeWithoutRoot "D:/Git/dcmtk/VisualStudio/bin/dcmsr_tests" "dcmsr_treeWithoutRoot")
set_tests_properties(dcmsr_treeWithoutRoot PROPERTIES  LABELS "dcmsr")
add_test(dcmsr_copyTree "D:/Git/dcmtk/VisualStudio/bin/dcmsr_tests" "dcmsr_copyTree")
set_tests_properties(dcmsr_copyTree PROPERTIES  LABELS "dcmsr")
add_test(dcmsr_cloneSubTree_1 "D:/Git/dcmtk/VisualStudio/bin/dcmsr_tests" "dcmsr_cloneSubTree_1")
set_tests_properties(dcmsr_cloneSubTree_1 PROPERTIES  LABELS "dcmsr")
add_test(dcmsr_cloneSubTree_2 "D:/Git/dcmtk/VisualStudio/bin/dcmsr_tests" "dcmsr_cloneSubTree_2")
set_tests_properties(dcmsr_cloneSubTree_2 PROPERTIES  LABELS "dcmsr")
add_test(dcmsr_extractSubTree "D:/Git/dcmtk/VisualStudio/bin/dcmsr_tests" "dcmsr_extractSubTree")
set_tests_properties(dcmsr_extractSubTree PROPERTIES  LABELS "dcmsr")
add_test(dcmsr_addContentItem "D:/Git/dcmtk/VisualStudio/bin/dcmsr_tests" "dcmsr_addContentItem")
set_tests_properties(dcmsr_addContentItem PROPERTIES  LABELS "dcmsr")
add_test(dcmsr_copyContentItem "D:/Git/dcmtk/VisualStudio/bin/dcmsr_tests" "dcmsr_copyContentItem")
set_tests_properties(dcmsr_copyContentItem PROPERTIES  LABELS "dcmsr")
add_test(dcmsr_gotoNamedNode "D:/Git/dcmtk/VisualStudio/bin/dcmsr_tests" "dcmsr_gotoNamedNode")
set_tests_properties(dcmsr_gotoNamedNode PROPERTIES  LABELS "dcmsr")
add_test(dcmsr_createDocSubTree "D:/Git/dcmtk/VisualStudio/bin/dcmsr_tests" "dcmsr_createDocSubTree")
set_tests_properties(dcmsr_createDocSubTree PROPERTIES  LABELS "dcmsr")
add_test(dcmsr_copyDocSubTree "D:/Git/dcmtk/VisualStudio/bin/dcmsr_tests" "dcmsr_copyDocSubTree")
set_tests_properties(dcmsr_copyDocSubTree PROPERTIES  LABELS "dcmsr")
add_test(dcmsr_cloneDocSubTree "D:/Git/dcmtk/VisualStudio/bin/dcmsr_tests" "dcmsr_cloneDocSubTree")
set_tests_properties(dcmsr_cloneDocSubTree PROPERTIES  LABELS "dcmsr")
add_test(dcmsr_insertDocSubTree_1 "D:/Git/dcmtk/VisualStudio/bin/dcmsr_tests" "dcmsr_insertDocSubTree_1")
set_tests_properties(dcmsr_insertDocSubTree_1 PROPERTIES  LABELS "dcmsr")
add_test(dcmsr_insertDocSubTree_2 "D:/Git/dcmtk/VisualStudio/bin/dcmsr_tests" "dcmsr_insertDocSubTree_2")
set_tests_properties(dcmsr_insertDocSubTree_2 PROPERTIES  LABELS "dcmsr")
add_test(dcmsr_insertDocSubTree_3 "D:/Git/dcmtk/VisualStudio/bin/dcmsr_tests" "dcmsr_insertDocSubTree_3")
set_tests_properties(dcmsr_insertDocSubTree_3 PROPERTIES  LABELS "dcmsr")
add_test(dcmsr_removeDocSubTree "D:/Git/dcmtk/VisualStudio/bin/dcmsr_tests" "dcmsr_removeDocSubTree")
set_tests_properties(dcmsr_removeDocSubTree PROPERTIES  LABELS "dcmsr")
add_test(dcmsr_extractDocSubTree_1 "D:/Git/dcmtk/VisualStudio/bin/dcmsr_tests" "dcmsr_extractDocSubTree_1")
set_tests_properties(dcmsr_extractDocSubTree_1 PROPERTIES  LABELS "dcmsr")
add_test(dcmsr_extractDocSubTree_2 "D:/Git/dcmtk/VisualStudio/bin/dcmsr_tests" "dcmsr_extractDocSubTree_2")
set_tests_properties(dcmsr_extractDocSubTree_2 PROPERTIES  LABELS "dcmsr")
add_test(dcmsr_extractAndInsertDocSubTree_1 "D:/Git/dcmtk/VisualStudio/bin/dcmsr_tests" "dcmsr_extractAndInsertDocSubTree_1")
set_tests_properties(dcmsr_extractAndInsertDocSubTree_1 PROPERTIES  LABELS "dcmsr")
add_test(dcmsr_extractAndInsertDocSubTree_2 "D:/Git/dcmtk/VisualStudio/bin/dcmsr_tests" "dcmsr_extractAndInsertDocSubTree_2")
set_tests_properties(dcmsr_extractAndInsertDocSubTree_2 PROPERTIES  LABELS "dcmsr")
add_test(dcmsr_changeDocumentType_1 "D:/Git/dcmtk/VisualStudio/bin/dcmsr_tests" "dcmsr_changeDocumentType_1")
set_tests_properties(dcmsr_changeDocumentType_1 PROPERTIES  LABELS "dcmsr")
add_test(dcmsr_changeDocumentType_2 "D:/Git/dcmtk/VisualStudio/bin/dcmsr_tests" "dcmsr_changeDocumentType_2")
set_tests_properties(dcmsr_changeDocumentType_2 PROPERTIES  LABELS "dcmsr")
