# CMake generated Testfile for 
# Source directory: D:/Git/dcmtk/ofstd/tests
# Build directory: D:/Git/dcmtk/VisualStudio/ofstd/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ofstd_OFCharacterEncoding_1 "D:/Git/dcmtk/VisualStudio/bin/ofstd_tests" "ofstd_OFCharacterEncoding_1")
set_tests_properties(ofstd_OFCharacterEncoding_1 PROPERTIES  LABELS "ofstd")
add_test(ofstd_OFCharacterEncoding_2 "D:/Git/dcmtk/VisualStudio/bin/ofstd_tests" "ofstd_OFCharacterEncoding_2")
set_tests_properties(ofstd_OFCharacterEncoding_2 PROPERTIES  LABELS "ofstd")
add_test(ofstd_OFCharacterEncoding_3 "D:/Git/dcmtk/VisualStudio/bin/ofstd_tests" "ofstd_OFCharacterEncoding_3")
set_tests_properties(ofstd_OFCharacterEncoding_3 PROPERTIES  LABELS "ofstd")
add_test(ofstd_OFCharacterEncoding_4 "D:/Git/dcmtk/VisualStudio/bin/ofstd_tests" "ofstd_OFCharacterEncoding_4")
set_tests_properties(ofstd_OFCharacterEncoding_4 PROPERTIES  LABELS "ofstd")
add_test(ofstd_OFCharacterEncoding_5 "D:/Git/dcmtk/VisualStudio/bin/ofstd_tests" "ofstd_OFCharacterEncoding_5")
set_tests_properties(ofstd_OFCharacterEncoding_5 PROPERTIES  LABELS "ofstd")
add_test(ofstd_OFCharacterEncoding_6 "D:/Git/dcmtk/VisualStudio/bin/ofstd_tests" "ofstd_OFCharacterEncoding_6")
set_tests_properties(ofstd_OFCharacterEncoding_6 PROPERTIES  LABELS "ofstd")
add_test(ofstd_OFCharacterEncoding_7 "D:/Git/dcmtk/VisualStudio/bin/ofstd_tests" "ofstd_OFCharacterEncoding_7")
set_tests_properties(ofstd_OFCharacterEncoding_7 PROPERTIES  LABELS "ofstd")
add_test(ofstd_OFCharacterEncoding_8 "D:/Git/dcmtk/VisualStudio/bin/ofstd_tests" "ofstd_OFCharacterEncoding_8")
set_tests_properties(ofstd_OFCharacterEncoding_8 PROPERTIES  LABELS "ofstd")
add_test(ofstd_OFDate "D:/Git/dcmtk/VisualStudio/bin/ofstd_tests" "ofstd_OFDate")
set_tests_properties(ofstd_OFDate PROPERTIES  LABELS "ofstd")
add_test(ofstd_OFDateTime "D:/Git/dcmtk/VisualStudio/bin/ofstd_tests" "ofstd_OFDateTime")
set_tests_properties(ofstd_OFDateTime PROPERTIES  LABELS "ofstd")
add_test(ofstd_OFList_1 "D:/Git/dcmtk/VisualStudio/bin/ofstd_tests" "ofstd_OFList_1")
set_tests_properties(ofstd_OFList_1 PROPERTIES  LABELS "ofstd")
add_test(ofstd_OFList_2 "D:/Git/dcmtk/VisualStudio/bin/ofstd_tests" "ofstd_OFList_2")
set_tests_properties(ofstd_OFList_2 PROPERTIES  LABELS "ofstd")
add_test(ofstd_OFList_splice "D:/Git/dcmtk/VisualStudio/bin/ofstd_tests" "ofstd_OFList_splice")
set_tests_properties(ofstd_OFList_splice PROPERTIES  LABELS "ofstd")
add_test(ofstd_OFMap "D:/Git/dcmtk/VisualStudio/bin/ofstd_tests" "ofstd_OFMap")
set_tests_properties(ofstd_OFMap PROPERTIES  LABELS "ofstd")
add_test(ofstd_OFStack "D:/Git/dcmtk/VisualStudio/bin/ofstd_tests" "ofstd_OFStack")
set_tests_properties(ofstd_OFStack PROPERTIES  LABELS "ofstd")
add_test(ofstd_OFStandard_isReadWriteable "D:/Git/dcmtk/VisualStudio/bin/ofstd_tests" "ofstd_OFStandard_isReadWriteable")
set_tests_properties(ofstd_OFStandard_isReadWriteable PROPERTIES  LABELS "ofstd")
add_test(ofstd_OFStandard_appendFilenameExtension "D:/Git/dcmtk/VisualStudio/bin/ofstd_tests" "ofstd_OFStandard_appendFilenameExtension")
set_tests_properties(ofstd_OFStandard_appendFilenameExtension PROPERTIES  LABELS "ofstd")
add_test(ofstd_OFStandard_removeRootDirFromPathname "D:/Git/dcmtk/VisualStudio/bin/ofstd_tests" "ofstd_OFStandard_removeRootDirFromPathname")
set_tests_properties(ofstd_OFStandard_removeRootDirFromPathname PROPERTIES  LABELS "ofstd")
add_test(ofstd_OFFile "D:/Git/dcmtk/VisualStudio/bin/ofstd_tests" "ofstd_OFFile")
set_tests_properties(ofstd_OFFile PROPERTIES  LABELS "ofstd")
add_test(ofstd_OFString_compare "D:/Git/dcmtk/VisualStudio/bin/ofstd_tests" "ofstd_OFString_compare")
set_tests_properties(ofstd_OFString_compare PROPERTIES  LABELS "ofstd")
add_test(ofstd_OFString_concatenate "D:/Git/dcmtk/VisualStudio/bin/ofstd_tests" "ofstd_OFString_concatenate")
set_tests_properties(ofstd_OFString_concatenate PROPERTIES  LABELS "ofstd")
add_test(ofstd_OFString_constructor "D:/Git/dcmtk/VisualStudio/bin/ofstd_tests" "ofstd_OFString_constructor")
set_tests_properties(ofstd_OFString_constructor PROPERTIES  LABELS "ofstd")
add_test(ofstd_OFString_copy "D:/Git/dcmtk/VisualStudio/bin/ofstd_tests" "ofstd_OFString_copy")
set_tests_properties(ofstd_OFString_copy PROPERTIES  LABELS "ofstd")
add_test(ofstd_OFString_identity_1 "D:/Git/dcmtk/VisualStudio/bin/ofstd_tests" "ofstd_OFString_identity_1")
set_tests_properties(ofstd_OFString_identity_1 PROPERTIES  LABELS "ofstd")
add_test(ofstd_OFString_identity_2 "D:/Git/dcmtk/VisualStudio/bin/ofstd_tests" "ofstd_OFString_identity_2")
set_tests_properties(ofstd_OFString_identity_2 PROPERTIES  LABELS "ofstd")
add_test(ofstd_OFString_identity_3 "D:/Git/dcmtk/VisualStudio/bin/ofstd_tests" "ofstd_OFString_identity_3")
set_tests_properties(ofstd_OFString_identity_3 PROPERTIES  LABELS "ofstd")
add_test(ofstd_OFString_reserve "D:/Git/dcmtk/VisualStudio/bin/ofstd_tests" "ofstd_OFString_reserve")
set_tests_properties(ofstd_OFString_reserve PROPERTIES  LABELS "ofstd")
add_test(ofstd_OFString_substr "D:/Git/dcmtk/VisualStudio/bin/ofstd_tests" "ofstd_OFString_substr")
set_tests_properties(ofstd_OFString_substr PROPERTIES  LABELS "ofstd")
add_test(ofstd_OFTime "D:/Git/dcmtk/VisualStudio/bin/ofstd_tests" "ofstd_OFTime")
set_tests_properties(ofstd_OFTime PROPERTIES  LABELS "ofstd")
add_test(ofstd_OFUUID_1 "D:/Git/dcmtk/VisualStudio/bin/ofstd_tests" "ofstd_OFUUID_1")
set_tests_properties(ofstd_OFUUID_1 PROPERTIES  LABELS "ofstd")
add_test(ofstd_OFUUID_2 "D:/Git/dcmtk/VisualStudio/bin/ofstd_tests" "ofstd_OFUUID_2")
set_tests_properties(ofstd_OFUUID_2 PROPERTIES  LABELS "ofstd")
add_test(ofstd_OFVector "D:/Git/dcmtk/VisualStudio/bin/ofstd_tests" "ofstd_OFVector")
set_tests_properties(ofstd_OFVector PROPERTIES  LABELS "ofstd")
add_test(ofstd_atof "D:/Git/dcmtk/VisualStudio/bin/ofstd_tests" "ofstd_atof")
set_tests_properties(ofstd_atof PROPERTIES  LABELS "ofstd")
add_test(ofstd_base64_1 "D:/Git/dcmtk/VisualStudio/bin/ofstd_tests" "ofstd_base64_1")
set_tests_properties(ofstd_base64_1 PROPERTIES  LABELS "ofstd")
add_test(ofstd_base64_2 "D:/Git/dcmtk/VisualStudio/bin/ofstd_tests" "ofstd_base64_2")
set_tests_properties(ofstd_base64_2 PROPERTIES  LABELS "ofstd")
add_test(ofstd_base64_3 "D:/Git/dcmtk/VisualStudio/bin/ofstd_tests" "ofstd_base64_3")
set_tests_properties(ofstd_base64_3 PROPERTIES  LABELS "ofstd")
add_test(ofstd_ftoa "D:/Git/dcmtk/VisualStudio/bin/ofstd_tests" "ofstd_ftoa")
set_tests_properties(ofstd_ftoa PROPERTIES  LABELS "ofstd")
add_test(ofstd_markup_1 "D:/Git/dcmtk/VisualStudio/bin/ofstd_tests" "ofstd_markup_1")
set_tests_properties(ofstd_markup_1 PROPERTIES  LABELS "ofstd")
add_test(ofstd_markup_2 "D:/Git/dcmtk/VisualStudio/bin/ofstd_tests" "ofstd_markup_2")
set_tests_properties(ofstd_markup_2 PROPERTIES  LABELS "ofstd")
add_test(ofstd_markup_3 "D:/Git/dcmtk/VisualStudio/bin/ofstd_tests" "ofstd_markup_3")
set_tests_properties(ofstd_markup_3 PROPERTIES  LABELS "ofstd")
add_test(ofstd_markup_4 "D:/Git/dcmtk/VisualStudio/bin/ofstd_tests" "ofstd_markup_4")
set_tests_properties(ofstd_markup_4 PROPERTIES  LABELS "ofstd")
add_test(ofstd_markup_5 "D:/Git/dcmtk/VisualStudio/bin/ofstd_tests" "ofstd_markup_5")
set_tests_properties(ofstd_markup_5 PROPERTIES  LABELS "ofstd")
add_test(ofstd_markup_6 "D:/Git/dcmtk/VisualStudio/bin/ofstd_tests" "ofstd_markup_6")
set_tests_properties(ofstd_markup_6 PROPERTIES  LABELS "ofstd")
add_test(ofstd_testPaths_1 "D:/Git/dcmtk/VisualStudio/bin/ofstd_tests" "ofstd_testPaths_1")
set_tests_properties(ofstd_testPaths_1 PROPERTIES  LABELS "ofstd")
add_test(ofstd_testPaths_2 "D:/Git/dcmtk/VisualStudio/bin/ofstd_tests" "ofstd_testPaths_2")
set_tests_properties(ofstd_testPaths_2 PROPERTIES  LABELS "ofstd")
add_test(ofstd_thread "D:/Git/dcmtk/VisualStudio/bin/ofstd_tests" "ofstd_thread")
set_tests_properties(ofstd_thread PROPERTIES  LABELS "ofstd")
add_test(ofstd_xmlParser "D:/Git/dcmtk/VisualStudio/bin/ofstd_tests" "ofstd_xmlParser")
set_tests_properties(ofstd_xmlParser PROPERTIES  LABELS "ofstd")
add_test(ofstd_memory "D:/Git/dcmtk/VisualStudio/bin/ofstd_tests" "ofstd_memory")
set_tests_properties(ofstd_memory PROPERTIES  LABELS "ofstd")
add_test(ofstd_optional "D:/Git/dcmtk/VisualStudio/bin/ofstd_tests" "ofstd_optional")
set_tests_properties(ofstd_optional PROPERTIES  LABELS "ofstd")
add_test(ofstd_tuple "D:/Git/dcmtk/VisualStudio/bin/ofstd_tests" "ofstd_tuple")
set_tests_properties(ofstd_tuple PROPERTIES  LABELS "ofstd")
add_test(ofstd_limits "D:/Git/dcmtk/VisualStudio/bin/ofstd_tests" "ofstd_limits")
set_tests_properties(ofstd_limits PROPERTIES  LABELS "ofstd")
